# Generated by Django 3.2.10 on 2024-06-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='elo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tourn_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
