# Generated by Django 4.2.13 on 2024-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='is_offline', max_length=10),
        ),
    ]
